# Generated by Django 2.2.2 on 2019-08-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': '口コミ', 'verbose_name_plural': '口コミ'},
        ),
        migrations.AlterModelTable(
            name='reviews',
            table='review',
        ),
    ]
