# Generated by Django 2.2.2 on 2019-08-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0002_auto_20190804_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
