# Generated by Django 2.2.2 on 2019-08-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0003_reviews_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='total_review',
            field=models.IntegerField(null=True),
        ),
    ]
