# Generated by Django 2.2.2 on 2019-08-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0004_reviews_total_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='total_review',
            field=models.IntegerField(default=1),
        ),
    ]
