# Generated by Django 2.2.2 on 2019-08-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0006_auto_20190809_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='total_review',
            field=models.FloatField(null=True),
        ),
    ]
