# Generated by Django 2.2.2 on 2019-08-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0007_auto_20190810_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='bath_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='beautiful_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='breakfast_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='dinner_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review_number',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='room_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='service_score',
            field=models.FloatField(null=True),
        ),
    ]
