# Generated by Django 2.2.2 on 2019-08-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0008_auto_20190810_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='dinner_score',
            new_name='夕食',
        ),
    ]
