# Generated by Django 2.2.2 on 2019-08-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0009_auto_20190810_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='夕食',
            new_name='dinner',
        ),
    ]
