# Generated by Django 2.2.2 on 2019-08-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0010_auto_20190810_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='dinner',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
