# Generated by Django 2.2.2 on 2019-08-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0011_auto_20190810_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='dinner',
            new_name='dinner_score',
        ),
    ]
