# Generated by Django 2.2.2 on 2019-08-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0012_auto_20190810_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='dinner_score',
            field=models.FloatField(blank=True, default='', null=True),
        ),
    ]
