# Generated by Django 2.2.2 on 2019-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0013_auto_20190810_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rank',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='yado_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='bath_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='beautiful_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='breakfast_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_number',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='room_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='service_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='total_review',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
