# Generated by Django 2.2.2 on 2019-08-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0014_auto_20190810_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='images',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='text',
        ),
    ]
