# Generated by Django 2.2.2 on 2019-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0015_auto_20190810_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='dinner_breakfast_lowest_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='stay_overnight_lowest_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
