# Generated by Django 2.2.2 on 2019-08-16 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0017_yado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraip.Yado'),
        ),
        migrations.AlterField(
            model_name='yado',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='宿の名前'),
        ),
    ]
