# Generated by Django 2.2.2 on 2019-08-16 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0018_auto_20190816_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='name',
            new_name='nam',
        ),
    ]
