# Generated by Django 2.2.2 on 2019-08-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0021_auto_20190819_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='yado_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
