# Generated by Django 2.2.2 on 2019-08-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0022_auto_20190819_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='yado_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
