# Generated by Django 2.2.2 on 2019-08-19 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraip', '0023_auto_20190819_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='エリア'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='bath_score',
            field=models.FloatField(blank=True, null=True, verbose_name='風呂'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='beautiful_score',
            field=models.FloatField(blank=True, null=True, verbose_name='清潔感'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='breakfast_score',
            field=models.FloatField(blank=True, null=True, verbose_name='朝食'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='dinner_breakfast_lowest_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1泊2食最安値'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='dinner_score',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='夕食'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraip.Yado', verbose_name='紐付け(名前)'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='掲載順位'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='口コミ数'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='room_score',
            field=models.FloatField(blank=True, null=True, verbose_name='部屋'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='service_score',
            field=models.FloatField(blank=True, null=True, verbose_name='サービス'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='stay_overnight_lowest_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='素泊まり最安値'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='total_review',
            field=models.FloatField(blank=True, null=True, verbose_name='総合得点'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='yado_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='yado',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='宿名'),
        ),
        migrations.AlterField(
            model_name='yado',
            name='yado_area',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='エリア'),
        ),
    ]
